name: Convert CSHTML to HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'

    - name: Build and run conversion script
      run: |
        dotnet run -p  /home/runner/work/Maks/Maks/ConsoleApplication1/ConsoleApp1/ConsoleApp1.csproj ${{ github.workspace }}/index.cshtml
